const mockProperties = [
    {
      id: 1,
      title: 'Sunny City Loft',
      type: 'City Rentals',
      location: 'New York, NY',
      price: 180,
      bedrooms: 1,
      bathrooms: 1,
      imageUrl: '/assets/cozy downtown.png',
      description: 'A bright, modern loft in the heart of the city.'
    },
    {
      id: 2,
      title: 'Cozy Apartment Retreat',
      type: 'Cozy Apartments',
      location: 'San Francisco, CA',
      price: 150,
      bedrooms: 2,
      bathrooms: 1,
      imageUrl: '/assets/cozy apartment.png',
      description: 'A comfortable apartment perfect for couples or small families.'
    },
    {
      id: 3,
      title: 'Luxury Penthouse',
      type: 'Luxury Living',
      location: 'Miami, FL',
      price: 500,
      bedrooms: 3,
      bathrooms: 2,
      imageUrl: '/assets/luxury living.png',
      description: 'Experience the high life in this stunning penthouse with ocean views.'
    },
    {
      id: 4,
      title: 'Budget Studio',
      type: 'Budget Friendly Stays',
      location: 'Austin, TX',
      price: 80,
      bedrooms: 1,
      bathrooms: 1,
      imageUrl: '/assets/budget friendly.png',
      description: 'Affordable and convenient studio for solo travelers.'
    },
    {
      id: 5,
      title: 'Nature Escape Cabin',
      type: 'Nature Escapes',
      location: 'Lake Tahoe, CA',
      price: 220,
      bedrooms: 2,
      bathrooms: 2,
      imageUrl: '/assets/nature escapes.png',
      description: 'A peaceful cabin surrounded by nature, perfect for relaxation.'
    },
    {
      id: 6,
      title: 'Family Vacation Home',
      type: 'Vacation Homes',
      location: 'Orlando, FL',
      price: 300,
      bedrooms: 4,
      bathrooms: 3,
      imageUrl: '/assets/vacation homes.png',
      description: 'Spacious home with a pool, ideal for family getaways.'
    },
    {
      id: 7,
      title: 'Downtown Budget Apartment',
      type: 'Budget Friendly Stays',
      location: 'Chicago, IL',
      price: 90,
      bedrooms: 1,
      bathrooms: 1,
      imageUrl: '/assets/budget friendly.png',
      description: 'Simple, clean, and close to public transport.'
    },
    {
      id: 8,
      title: 'Mountain View Retreat',
      type: 'Nature Escapes',
      location: 'Denver, CO',
      price: 200,
      bedrooms: 3,
      bathrooms: 2,
      imageUrl: '/assets/nature escapes.png',
      description: 'Enjoy mountain views and fresh air in this cozy retreat.'
    },
    {
      id: 9,
      title: 'Elegant City Apartment',
      type: 'Cozy Apartments',
      location: 'Boston, MA',
      price: 170,
      bedrooms: 2,
      bathrooms: 1,
      imageUrl: '/assets/cozy apartment.png',
      description: 'Elegant apartment with easy access to city attractions.'
    },
    {
      id: 10,
      title: 'Beachside Luxury Villa',
      type: 'Luxury Living',
      location: 'Malibu, CA',
      price: 700,
      bedrooms: 5,
      bathrooms: 4,
      imageUrl: '/assets/luxury living.png',
      description: 'A stunning villa right on the beach with premium amenities.'
    },
    {
      id: 11,
      title: 'Urban Studio',
      type: 'City Rentals',
      location: 'Seattle, WA',
      price: 120,
      bedrooms: 1,
      bathrooms: 1,
      imageUrl: '/assets/cozy downtown.png',
      description: 'Compact studio in the heart of downtown.'
    },
    {
      id: 12,
      title: 'Chic Apartment',
      type: 'Cozy Apartments',
      location: 'Portland, OR',
      price: 140,
      bedrooms: 1,
      bathrooms: 1,
      imageUrl: '/assets/cozy apartment.png',
      description: 'Stylish apartment with modern amenities.'
    },
    {
      id: 13,
      title: 'Luxury Downtown Condo',
      type: 'Luxury Living',
      location: 'Dallas, TX',
      price: 450,
      bedrooms: 2,
      bathrooms: 2,
      imageUrl: '/assets/luxury living.png',
      description: 'High-rise condo with city views.'
    },
    {
      id: 14,
      title: 'Budget Traveler Room',
      type: 'Budget Friendly Stays',
      location: 'Las Vegas, NV',
      price: 60,
      bedrooms: 1,
      bathrooms: 1,
      imageUrl: '/assets/budget friendly.png',
      description: 'Perfect for budget travelers.'
    },
    {
      id: 15,
      title: 'Forest Hideaway',
      type: 'Nature Escapes',
      location: 'Asheville, NC',
      price: 180,
      bedrooms: 2,
      bathrooms: 1,
      imageUrl: '/assets/nature escapes.png',
      description: 'Secluded cabin in the woods.'
    },
    {
      id: 16,
      title: 'Disney Family Home',
      type: 'Vacation Homes',
      location: 'Kissimmee, FL',
      price: 320,
      bedrooms: 5,
      bathrooms: 4,
      imageUrl: '/assets/vacation homes.png',
      description: 'Minutes from Disney parks.'
    },
    {
      id: 17,
      title: 'Budget City Room',
      type: 'Budget Friendly Stays',
      location: 'Philadelphia, PA',
      price: 70,
      bedrooms: 1,
      bathrooms: 1,
      imageUrl: '/assets/budget friendly.png',
      description: 'Affordable room in the city.'
    },
    {
      id: 18,
      title: 'Lakeview Nature Lodge',
      type: 'Nature Escapes',
      location: 'Lake Placid, NY',
      price: 210,
      bedrooms: 3,
      bathrooms: 2,
      imageUrl: '/assets/nature escapes.png',
      description: 'Lodge with lake views.'
    },
    {
      id: 19,
      title: 'Modern City Flat',
      type: 'City Rentals',
      location: 'London, UK',
      price: 220,
      bedrooms: 2,
      bathrooms: 1,
      imageUrl: '/assets/cozy downtown.png',
      description: 'Modern flat in central London.'
    },
    {
      id: 20,
      title: 'Parisian Apartment',
      type: 'Cozy Apartments',
      location: 'Paris, France',
      price: 210,
      bedrooms: 1,
      bathrooms: 1,
      imageUrl: '/assets/cozy apartment.png',
      description: 'Charming apartment in Paris.'
    },
    {
      id: 21,
      title: 'Luxury Beach Condo',
      type: 'Luxury Living',
      location: 'Gold Coast, Australia',
      price: 600,
      bedrooms: 4,
      bathrooms: 3,
      imageUrl: '/assets/luxury living.png',
      description: 'Beachfront luxury condo.'
    },
    {
      id: 22,
      title: 'Budget Hostel Room',
      type: 'Budget Friendly Stays',
      location: 'Berlin, Germany',
      price: 50,
      bedrooms: 1,
      bathrooms: 1,
      imageUrl: '/assets/budget friendly.png',
      description: 'Simple hostel room.'
    },
    {
      id: 23,
      title: 'Mountain Escape',
      type: 'Nature Escapes',
      location: 'Zermatt, Switzerland',
      price: 350,
      bedrooms: 3,
      bathrooms: 2,
      imageUrl: '/assets/nature escapes.png',
      description: 'Chalet with mountain views.'
    },
    {
      id: 24,
      title: 'Orlando Resort Home',
      type: 'Vacation Homes',
      location: 'Orlando, FL',
      price: 330,
      bedrooms: 4,
      bathrooms: 3,
      imageUrl: '/assets/vacation homes.png',
      description: 'Resort-style vacation home.'
    },
    {
      id: 25,
      title: 'Budget Guesthouse',
      type: 'Budget Friendly Stays',
      location: 'Bangkok, Thailand',
      price: 40,
      bedrooms: 1,
      bathrooms: 1,
      imageUrl: '/assets/budget friendly.png',
      description: 'Affordable guesthouse.'
    },
    {
      id: 26,
      title: 'Jungle Nature Retreat',
      type: 'Nature Escapes',
      location: 'Ubud, Bali',
      price: 250,
      bedrooms: 2,
      bathrooms: 2,
      imageUrl: '/assets/nature escapes.png',
      description: 'Retreat in the jungle.'
    },
    {
      id: 27,
      title: 'Tokyo City Studio',
      type: 'City Rentals',
      location: 'Tokyo, Japan',
      price: 160,
      bedrooms: 1,
      bathrooms: 1,
      imageUrl: '/assets/cozy downtown.png',
      description: 'Studio in central Tokyo.'
    },
    {
      id: 28,
      title: 'Barcelona Apartment',
      type: 'Cozy Apartments',
      location: 'Barcelona, Spain',
      price: 180,
      bedrooms: 2,
      bathrooms: 1,
      imageUrl: '/assets/cozy apartment.png',
      description: 'Sunny apartment in Barcelona.'
    },
    {
      id: 29,
      title: 'Luxury Lake Villa',
      type: 'Luxury Living',
      location: 'Como, Italy',
      price: 800,
      bedrooms: 6,
      bathrooms: 5,
      imageUrl: '/assets/luxury living.png',
      description: 'Villa on Lake Como.'
    },
    {
      id: 30,
      title: 'Budget Capsule',
      type: 'Budget Friendly Stays',
      location: 'Tokyo, Japan',
      price: 35,
      bedrooms: 1,
      bathrooms: 1,
      imageUrl: '/assets/budget friendly.png',
      description: 'Capsule hotel experience.'
    },
    {
      id: 31,
      title: 'Rainforest Nature Home',
      type: 'Nature Escapes',
      location: 'Amazonas, Brazil',
      price: 270,
      bedrooms: 3,
      bathrooms: 2,
      imageUrl: '/assets/nature escapes.png',
      description: 'Home in the rainforest.'
    },
    {
      id: 32,
      title: 'Disney Villa',
      type: 'Vacation Homes',
      location: 'Anaheim, CA',
      price: 340,
      bedrooms: 5,
      bathrooms: 4,
      imageUrl: '/assets/vacation homes.png',
      description: 'Villa near Disneyland.'
    },
    {
      id: 33,
      title: 'Budget Beach Hut',
      type: 'Budget Friendly Stays',
      location: 'Goa, India',
      price: 55,
      bedrooms: 1,
      bathrooms: 1,
      imageUrl: '/assets/budget friendly.png',
      description: 'Beach hut for budget travelers.'
    },
    {
      id: 34,
      title: 'Safari Nature Lodge',
      type: 'Nature Escapes',
      location: 'Nairobi, Kenya',
      price: 260,
      bedrooms: 2,
      bathrooms: 2,
      imageUrl: '/assets/nature escapes.png',
      description: 'Lodge near safari parks.'
    },
    {
      id: 35,
      title: 'Sydney City Apartment',
      type: 'City Rentals',
      location: 'Sydney, Australia',
      price: 210,
      bedrooms: 2,
      bathrooms: 2,
      imageUrl: '/assets/cozy downtown.png',
      description: 'Apartment in downtown Sydney.'
    },
    {
      id: 36,
      title: 'Vienna Cozy Flat',
      type: 'Cozy Apartments',
      location: 'Vienna, Austria',
      price: 160,
      bedrooms: 1,
      bathrooms: 1,
      imageUrl: '/assets/cozy apartment.png',
      description: 'Cozy flat in Vienna.'
    },
    {
      id: 37,
      title: 'Luxury Palace Suite',
      type: 'Luxury Living',
      location: 'Dubai, UAE',
      price: 1200,
      bedrooms: 7,
      bathrooms: 6,
      imageUrl: '/assets/luxury living.png',
      description: 'Palace suite with luxury amenities.'
    },
    {
      id: 38,
      title: 'Budget Downtown Room',
      type: 'Budget Friendly Stays',
      location: 'Toronto, Canada',
      price: 75,
      bedrooms: 1,
      bathrooms: 1,
      imageUrl: '/assets/budget friendly.png',
      description: 'Affordable room in downtown Toronto.'
    },
    {
      id: 39,
      title: 'Alpine Nature Chalet',
      type: 'Nature Escapes',
      location: 'Innsbruck, Austria',
      price: 230,
      bedrooms: 3,
      bathrooms: 2,
      imageUrl: '/assets/nature escapes.png',
      description: 'Chalet in the Alps.'
    },
    {
      id: 40,
      title: 'Orlando Family Resort',
      type: 'Vacation Homes',
      location: 'Orlando, FL',
      price: 310,
      bedrooms: 4,
      bathrooms: 3,
      imageUrl: '/assets/vacation homes.png',
      description: 'Family-friendly resort home.'
    },
  ];
  export default mockProperties;
  